---
- name: make repo dir
  file:
    path: "{{ item }}"
    owner: root
    group: root
    mode: 0655
    state: directory
  with_items: "{{ repo_dir }}"

- name: format repo dir
  shell: createrepo -pdo "{{ item }}" "{{ item }}"
  args:
    creates: "{{ item }}/repodata"
  with_items: "{{ repo_dir }}"

- name: copy repo configure
  template:
    src: 37dz.repo.j2
    dest: /etc/yum.repos.d/37dz.repo
    owner: root
    group: root
    mode: 0644
